Repository 15thmeu/Liberation, pull requests merged in 2020-10, with the labels that each got.

#4 Updated Starting Base compositions
  Missionbasefiles/15th_liberation.Abramia/mission.sqm
  Missionbasefiles/15th_liberation.Altis/mission.sqm
  Missionbasefiles/15th_liberation.Chernarus/mission.sqm
  Missionbasefiles/15th_liberation.Lingor3/mission.sqm
  Missionbasefiles/15th_liberation.Malden/mission.sqm
  Missionbasefiles/15th_liberation.Sara/mission.sqm
  Missionbasefiles/15th_liberation.Takistan/mission.sqm
Labels: bug

#26 Oats Uniform
  Missionframework/arsenal_presets/custom.sqf
Labels: armory

#29 Added AAVP-7A1 to starting compositions
  Missionbasefiles/15th_liberation.Abramia/mission.sqm
  Missionbasefiles/15th_liberation.Altis/mission.sqm
  Missionbasefiles/15th_liberation.Chernarus/mission.sqm
  Missionbasefiles/15th_liberation.Lingor3/mission.sqm
  Missionbasefiles/15th_liberation.Malden/mission.sqm
  Missionbasefiles/15th_liberation.Sara/mission.sqm
  Missionbasefiles/15th_liberation.Takistan/mission.sqm
Labels: enhancement
